# Generated by Django 4.0.2 on 2022-03-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguist', '0002_auto_20170126_0355'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='translation',
            index_together={('identifier', 'object_id'), ('identifier', 'object_id', 'field_name')},
        ),
        migrations.AlterField(
            model_name='translation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], db_index=True, default='en', help_text='The language for this translation', max_length=10, verbose_name='language'),
        ),
    ]
