language: python
services: postgresql
env:
    - TOXENV=py26-django16
    - TOXENV=py27-django16
    - TOXENV=py33-django16
    - TOXENV=py34-django16
    - TOXENV=py27-django17
    - TOXENV=py33-django17
    - TOXENV=py34-django17
    - TOXENV=py27-django18
    - TOXENV=py33-django18
    - TOXENV=py34-django18
install:
    - travis_retry pip install tox
script:
    - travis_retry tox
